/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PilotoViewImpl.java
 *
 * Created on 23-nov-2009, 9:47:30
 */
package vista.piloto;

import controlador.PilotoController;
import vista.AbstractViewImpl;
import java.util.ArrayList;
import java.util.List;
import modelo.PilotoModel;
import modelo.entidades.Piloto;

/**
 *
 * @author Norberto Díaz-Díaz
 */
public class PilotoViewImpl extends AbstractViewImpl<PilotoController, PilotoModel> implements PilotoView {

    //Atributos propios de Swing
    private PilotoTableAndComboModel tableModel;
    private PilotoViewImplInternal panelCliente;

    /** Creates new form PilotoViewImpl */
    public PilotoViewImpl() {
        //tableModel = new PilotoTableAndComboModel();
        tableModel = PilotoTableAndComboModel.create();
        initComponents();

        this.panelCliente = new PilotoViewImplInternal(this);
        this.jPanelCliente.add(this.panelCliente);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePilotos = new javax.swing.JTable();
        jPanelCliente = new javax.swing.JPanel();

        jTablePilotos.setModel(tableModel);
        jTablePilotos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePilotosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePilotos);

        jPanelCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelCliente.setLayout(new javax.swing.BoxLayout(jPanelCliente, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePilotosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePilotosMouseClicked
        PilotoTableAndComboModel ctm = (PilotoTableAndComboModel) this.jTablePilotos.getModel();
        Piloto piloto = ctm.getRow(this.jTablePilotos.getSelectedRow());
        panelCliente.setEntidad(piloto);
    }//GEN-LAST:event_jTablePilotosMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePilotos;
    // End of variables declaration//GEN-END:variables

    public void refresh() {
        tableModel.setPilotos(getModel().listar());//cambia el modelo de JTable(TableModel) por medio de una clase que hemos creado (ContactosTableModel)
    }

    protected void fireNuevoClienteGesture(String DNI, String nombre) {
        List<String> datos = new ArrayList<String>();
        datos.add(DNI);
        datos.add(nombre);
        getController().nuevaEntidadGesture(datos);
    }

    protected void fireActualizaClienteGesture(String DNI, String nombre) {
        List<String> datos = new ArrayList<String>();
        datos.add(DNI);
        datos.add(nombre);
        getController().actualizaEntidadGesture(datos);
    }

    protected void fireBorraClienteGesture(String nombre) {
        getController().borraEntidadGesture(nombre);
    }
}
