/*
 * VentanaPrincipal.java
 *
 * Created on 27 de octubre de 2008, 14:24
 */
package vista;

import controlador.ClienteController;
import modelo.Cliente;
import modelo.ClienteModel;

/**
 *
 * @author  Norberto Díaz-Díaz
 */
public class ClienteViewImpl extends javax.swing.JFrame implements ClienteView {
    //Atributos del MVC

    private ClienteModel model;
    private ClienteController controller;

    //Atributos propios de Swing
    private ClientesTableModel tableModel;
    private JPanelCliente panelCliente;

    /** Creates new form VentanaPrincipal */
    public ClienteViewImpl() {
        tableModel = new ClientesTableModel();
        initComponents();

        this.panelCliente = new JPanelCliente(this);
        this.jPanelDown.add(this.panelCliente);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDown = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Contactos");

        jPanelDown.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelDown.setLayout(new javax.swing.BoxLayout(jPanelDown, javax.swing.BoxLayout.LINE_AXIS));

        jTableClientes.setModel(tableModel);
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanelDown, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE)
                .add(jPanelDown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 280, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        // TODO add your handling code here:
        ClientesTableModel ctm = (ClientesTableModel) this.jTableClientes.getModel();
        Cliente cliente = ctm.getRow(this.jTableClientes.getSelectedRow());
        panelCliente.setCliente(cliente);
    }//GEN-LAST:event_jTableClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ClienteViewImpl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelDown;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables

    public ClienteController getController() {
        return controller;
    }

    public void setController(ClienteController controller) {
        this.controller = controller;
    }

    public ClienteModel getModel() {
        return model;
    }

    public void setModel(ClienteModel model) {
        this.model = model;
    }

    public void dataModelChanged() {
        refresh();
    }

    public void display() {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                setVisible(true);
                refresh();
            }
        });
    }

    protected void refresh() {
        tableModel.setClientes(getModel().obtenerClientes());//cambia el modelo de JTable(TableModel) por medio de una clase que hemos creado (ClientesTableModel)
    }

    protected void fireNuevoClienteGesture(String nombre, String tlf, String email) {
        getController().nuevoClienteGesture(nombre, tlf, email);
    }

    protected void fireActualizaClienteGesture(String nombre, String tlf, String email) {
        getController().actualizaClienteGesture(nombre, tlf, email);
    }

    protected void fireBorraClienteGesture(String nombre) {
        getController().borraClienteGesture(nombre);
    }
}
