/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClienteViewImpl.java
 *
 * Created on 23-nov-2009, 9:47:30
 */
package vista.circuito;

import controlador.CircuitoController;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import modelo.CircuitoModel;
import modelo.entidades.Circuito;
import modelo.entidades.Piloto;
import vista.AbstractViewImpl;
import vista.piloto.PilotoTableAndComboModel;

/**
 *
 * @author Norberto Díaz-Díaz
 */
public class CircuitoViewImpl extends AbstractViewImpl<CircuitoController, CircuitoModel> implements CircuitoView {

    //Atributos propios de Swing
    private CircuitoTableModel circuitoTableModel;
    private CircuitoViewImplInternal panelCircuito;
    private PilotoTableAndComboModel piloto1ComboModel;
    private PilotoTableAndComboModel piloto2ComboModel;
    private PilotoTableAndComboModel piloto3ComboModel;
    private PilotoTableAndComboModel pilotoComboModel;

    /** Creates new form ClienteViewImpl */
    public CircuitoViewImpl() {
        circuitoTableModel = new CircuitoTableModel();
        //comboModel = new ClienteTableAndComboModel();
        pilotoComboModel=PilotoTableAndComboModel.create();
        piloto1ComboModel=PilotoTableAndComboModel.create();
        piloto2ComboModel=PilotoTableAndComboModel.create();
        piloto3ComboModel=PilotoTableAndComboModel.create();
        initComponents();

        this.panelCircuito = new CircuitoViewImplInternal(this);
        this.jPanelFactura.add(this.panelCircuito);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCircuitos = new javax.swing.JTable();
        jPanelFactura = new javax.swing.JPanel();
        jComboBoxPiloto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButtonFiltrar = new javax.swing.JButton();
        jButtonQuitarFiltro = new javax.swing.JButton();

        jTableCircuitos.setModel(circuitoTableModel);
        jTableCircuitos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCircuitosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCircuitos);

        jPanelFactura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelFactura.setLayout(new javax.swing.BoxLayout(jPanelFactura, javax.swing.BoxLayout.LINE_AXIS));

        jComboBoxPiloto.setModel(pilotoComboModel);

        jLabel1.setText("Piloto");

        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });

        jButtonQuitarFiltro.setText("QuitarFiltro");
        jButtonQuitarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxPiloto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jButtonFiltrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonQuitarFiltro)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFiltrar)
                            .addComponent(jButtonQuitarFiltro))))
                .addGap(18, 18, 18)
                .addComponent(jPanelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCircuitosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCircuitosMouseClicked
        CircuitoTableModel ctm = (CircuitoTableModel) this.jTableCircuitos.getModel();
        Circuito circuito = ctm.getRow(this.jTableCircuitos.getSelectedRow());
        panelCircuito.setCircuito(circuito);
    }//GEN-LAST:event_jTableCircuitosMouseClicked

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        PilotoTableAndComboModel ccm=(PilotoTableAndComboModel)this.jComboBoxPiloto.getModel();
        Piloto piloto= ccm.getRow(this.jComboBoxPiloto.getSelectedIndex());
        List<Circuito> circuitos=((CircuitoModel)getModel()).listarPorPuntuados(piloto);
        circuitoTableModel.setCircuitos(circuitos);
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    private void jButtonQuitarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarFiltroActionPerformed
        refresh();
    }//GEN-LAST:event_jButtonQuitarFiltroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonQuitarFiltro;
    private javax.swing.JComboBox jComboBoxPiloto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCircuitos;
    // End of variables declaration//GEN-END:variables

    protected PilotoTableAndComboModel getComboModelPiloto1() {
        return piloto1ComboModel;
    }

    protected PilotoTableAndComboModel getComboModelPiloto2() {
        return piloto2ComboModel;
    }
    protected PilotoTableAndComboModel getComboModelPiloto3() {
        return piloto3ComboModel;
    }
    

    public void refresh() {
        circuitoTableModel.setCircuitos(getModel().listar());//cambia el modelo de JTable(TableModel) por medio de una clase que hemos creado (ContactosTableModel)
    }

    protected void fireNuevaFacturaGesture(String nombre, String ubicacion, Piloto primero, Piloto segundo, Piloto tercero){
        List<Serializable> datos = new ArrayList<Serializable>();
        datos.add(nombre);
        datos.add(ubicacion);
        datos.add(primero);
        datos.add(segundo);
        datos.add(tercero);
        getController().nuevaEntidadGesture(datos);
    }

    protected void fireActualizaFacturaGesture(String nombre, String ubicacion, Piloto primero, Piloto segundo, Piloto tercero) {
        List<Serializable> datos = new ArrayList<Serializable>();
        datos.add(nombre);
        datos.add(ubicacion);
        datos.add(primero);
        datos.add(segundo);
        datos.add(tercero);
        getController().actualizaEntidadGesture(datos);
    }

    protected void fireBorraFacturaGesture(String identificador) {
        getController().borraEntidadGesture(identificador);
    }
}
