/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaGlobal.java
 *
 * Created on 23-nov-2009, 11:03:25
 */

package vista;


import javax.swing.JPanel;
import vista.circuito.CircuitoView;

import vista.piloto.PilotoView;


/**
 *
 * @author Norberto Díaz-Díaz
 */
public class VistaGlobalTabbed extends javax.swing.JFrame /*implements ClienteView*/{
    private PilotoView pilotoView;
    private CircuitoView circuitoView;

    /** Creates new form VistaGlobal */
    public VistaGlobalTabbed(PilotoView pilotoView, CircuitoView circuitoView) {
        this.pilotoView=pilotoView;
        this.circuitoView=circuitoView;
        initComponents();
        this.jTabbedPanel.add("piloto",(JPanel)pilotoView);
        this.jTabbedPanel.add("circuito", (JPanel)circuitoView);
        this.setTitle("Aplicación para la Formula1");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPanelMouseClicked
       if(this.jTabbedPanel.getSelectedIndex()==1)
        circuitoView.display();
    }//GEN-LAST:event_jTabbedPanelMouseClicked

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPanel;
    // End of variables declaration//GEN-END:variables


 
    public void display() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                pilotoView.display();
                //facturaView.display();
            }
        });
        
    }
}
