/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaGlobal.java
 *
 * Created on 23-nov-2009, 11:03:25
 */

package vista;


import javax.swing.JPanel;
import vista.circuito.CircuitoView;

import vista.piloto.PilotoView;


/**
 *
 * @author Norberto Díaz-Díaz
 */
public class VistaGlobal extends javax.swing.JFrame /*implements ClienteView*/{
    private PilotoView pilotoView;
    private CircuitoView circuitoView;

    /** Creates new form VistaGlobal */
    public VistaGlobal(PilotoView pilotoView, CircuitoView circuitoView) {
        this.pilotoView=pilotoView;
        this.circuitoView=circuitoView;
        initComponents();
        this.add("piloto",(JPanel)pilotoView);
        this.add("circuito", (JPanel)circuitoView);
        this.setTitle("Aplicación para la Formula1");
        this.setSize(1200, 500);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


 
    public void display() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                pilotoView.display();
                circuitoView.display();
                //facturaView.display();
            }
        });
        
    }
}
